[package]
name = "jira"
version = "0.0.0"
description = "Jira API"
authors = ["MrRefactoring <MrRefactoring@yandex.ru>"]
edition = "2018"
license = "MIT"

[dependencies]
oauth2 = "1.3.0"
reqwest = "0.9.9"
